In [3]:
import numpy as np

In [5]:
#Array 1 Dimensão
d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [7]:
d1.shape # Formato do Array

(3,)

In [9]:
#Numero de dimensões
d1.ndim

1

In [15]:
#Array de 2 Dimensões
d2 = np.array([[1,2,3],[4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [19]:
# Array de 3 Dimensões
d3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
#Somando Arrays
a = np.array([2,3,4])
b = np.array([2,4,6])
#Vamos somar as colunas de array
result = np.add(a,b)
print(result)

[ 4  7 10]


In [29]:
#Selecionando itens em um array
resultado = np.array([[2,3,4,5],[6,7,8,9]])
print(resultado)

[[2 3 4 5]
 [6 7 8 9]]


In [31]:
#Array[row, colu]
resultado[1,2]

8

In [33]:
#Selecionando uma row
resultado[0,:]

array([2, 3, 4, 5])

In [35]:
resultado[:,2]

array([4, 8])